// ----- City actions -----
export const CITY_SEARCH_LOAD_INIT = 'CITY_SEARCH_LOAD_INIT';
export const CITY_SEARCH_LOAD_SUCCESS = 'CITY_SEARCH_LOAD_SUCCESS';
export const CITY_SEARCH_LOAD_FAILED = 'CITY_SEARCH_LOAD_FAILED';

export const CITY_RESET_STATE = 'CITY_RESET_STATE'; 

// ----- Forecast actions -----

export const FORECAST_LOAD_INIT = 'FORECAST_LOAD_INIT';
export const FORECAST_LOAD_SUCCESS = 'FORECAST_LOAD_SUCCESS';
export const FORECAST_LOAD_FAILED = 'FORECAST_LOAD_FAILED';

export const FORECAST_RESET_STATE = 'FORECAST_RESET_STATE'; 