export const LOGIN_LOAD_INIT = 'LOGIN_LOAD_INIT'
export const LOGIN_LOAD_SUCCESS = 'LOGIN_LOAD_SUCCESS'
export const LOGIN_LOAD_FAILED = 'LOGIN_LOAD_FAILED'

export const REGISTER_LOAD_INIT = 'REGISTER_LOAD_INIT'
export const REGISTER_SAVE_SUCCESS = 'REGISTER_SAVE_SUCCESS'
export const REGISTER_LOAD_FAILED = 'REGISTER_LOAD_FAILED'

export const LOGIN_RESET_STATE = 'LOGIN_RESET_STATE'